version: "3.7"

services:
        nodejs:
                container_name: nodejs
                image: "my_express_app"
                volumes:
                        - ./node_app_local:/app 

        nginx: 
                container_name: nginx
                image: "my_nginx"
                ports:
                        - "8080:80" 
        kurento:
                container_name: kurento
                image: "kurento/kurento-media-server:latest"
                network_mode: "host"
