version: "3.7"

services:

        kurento:
                container_name: kurento
                image: "kurento/kurento-media-server:latest"
                network_mode: "host"
                volumes:
                  - type: bind
                    source: ./etc-kurento
                    target: /etc/kurento
                  - type: bind
                    source: ./tmp
                    target: /tmp

